namespace YaziDesktopHost;

internal static class YaziDefaultManagerCommands
{
    internal const string PinnedYaziVersion = "26.5.6";
    internal const string SourcePath = "yazi-config/preset/keymap-default.toml ([mgr].keymap)";
    internal const string SourceUrl = "https://raw.githubusercontent.com/sxyazi/yazi/v26.5.6/yazi-config/preset/keymap-default.toml";

    internal static IReadOnlyList<YaziBridgeCommand> Commands { get; } =
    [
        new("<Esc> / <C-[>", "escape", "Exit visual mode, clear selection, or cancel search"),
        new("q", "quit", "Quit the process"),
        new("Q", "quit --no-cwd-file", "Quit without outputting cwd-file"),
        new("<C-c>", "close", "Close the current tab, or quit if it's last"),
        new("<C-z>", "suspend", "Suspend the process"),
        new("k / <Up>", "arrow prev", "Previous file"),
        new("j / <Down>", "arrow next", "Next file"),
        new("<C-u> / <S-PageUp>", "arrow -50%", "Move cursor up half page"),
        new("<C-d> / <S-PageDown>", "arrow 50%", "Move cursor down half page"),
        new("<C-b> / <PageUp>", "arrow -100%", "Move cursor up one page"),
        new("<C-f> / <PageDown>", "arrow 100%", "Move cursor down one page"),
        new("g + g", "arrow top", "Go to top"),
        new("G", "arrow bot", "Go to bottom"),
        new("h / <Left>", "leave", "Back to the parent directory"),
        new("l / <Right>", "enter", "Enter the child directory"),
        new("H", "back", "Back to previous directory"),
        new("L", "forward", "Forward to next directory"),
        new("<Space>", "toggle", "Toggle the current selection state", ["toggle", "arrow 1"]),
        new("<C-a>", "toggle_all --state=on", "Select all files"),
        new("<C-r>", "toggle_all", "Invert selection of all files"),
        new("v", "visual_mode", "Enter visual mode (selection mode)"),
        new("V", "visual_mode --unset", "Enter visual mode (unset mode)"),
        new("K", "seek -5", "Seek up 5 units in the preview"),
        new("J", "seek 5", "Seek down 5 units in the preview"),
        new("<Tab>", "spot", "Spot hovered file"),
        new("o / <Enter>", "open", "Open selected files"),
        new("O / <S-Enter>", "open --interactive", "Open selected files interactively"),
        new("y", "yank", "Yank selected files (copy)"),
        new("x", "yank --cut", "Yank selected files (cut)"),
        new("p", "paste", "Paste yanked files"),
        new("P", "paste --force", "Paste yanked files (overwrite if the destination exists)"),
        new("-", "link", "Symlink the absolute path of yanked files"),
        new("_", "link --relative", "Symlink the relative path of yanked files"),
        new("<C-->", "hardlink", "Hardlink yanked files"),
        new("Y / X", "unyank", "Cancel the yank status"),
        new("d", "remove", "Trash selected files"),
        new("D", "remove --permanently", "Permanently delete selected files"),
        new("a", "create", "Create a file (ends with / for directories)"),
        new("r", "rename --cursor=before_ext", "Rename selected file(s)"),
        new(";", "shell --interactive", "Run a shell command"),
        new(":", "shell --block --interactive", "Run a shell command (block until finishes)"),
        new(".", "hidden toggle", "Toggle the visibility of hidden files"),
        new("s", "search --via=fd", "Search files by name via fd"),
        new("S", "search --via=rg", "Search files by content via ripgrep"),
        new("<C-s>", "escape --search", "Cancel the ongoing search"),
        new("z", "plugin fzf", "Jump to a file/directory via fzf"),
        new("Z", "plugin zoxide", "Jump to a directory via zoxide"),
        new("m + s", "linemode size", "Linemode: size"),
        new("m + p", "linemode permissions", "Linemode: permissions"),
        new("m + b", "linemode btime", "Linemode: btime"),
        new("m + m", "linemode mtime", "Linemode: mtime"),
        new("m + o", "linemode owner", "Linemode: owner"),
        new("m + n", "linemode none", "Linemode: none"),
        new("c + c", "copy path", "Copy file URL"),
        new("c + d", "copy dirname", "Copy directory URL"),
        new("c + f", "copy filename", "Copy filename"),
        new("c + n", "copy name_without_ext", "Copy filename without extension"),
        new("f", "filter --smart", "Filter files"),
        new("/", "find --smart", "Find next file"),
        new("?", "find --previous --smart", "Find previous file"),
        new("n", "find_arrow", "Next found"),
        new("N", "find_arrow --previous", "Previous found"),
        new(", + m", "sort mtime --reverse=no", "Sort by modified time", ["sort mtime --reverse=no", "linemode mtime"]),
        new(", + M", "sort mtime --reverse=yes", "Sort by modified time (reverse)", ["sort mtime --reverse=yes", "linemode mtime"]),
        new(", + b", "sort btime --reverse=no", "Sort by birth time", ["sort btime --reverse=no", "linemode btime"]),
        new(", + B", "sort btime --reverse=yes", "Sort by birth time (reverse)", ["sort btime --reverse=yes", "linemode btime"]),
        new(", + e", "sort extension --reverse=no", "Sort by extension"),
        new(", + E", "sort extension --reverse=yes", "Sort by extension (reverse)"),
        new(", + a", "sort alphabetical --reverse=no", "Sort alphabetically"),
        new(", + A", "sort alphabetical --reverse=yes", "Sort alphabetically (reverse)"),
        new(", + n", "sort natural --reverse=no", "Sort naturally"),
        new(", + N", "sort natural --reverse=yes", "Sort naturally (reverse)"),
        new(", + s", "sort size --reverse=no", "Sort by size", ["sort size --reverse=no", "linemode size"]),
        new(", + S", "sort size --reverse=yes", "Sort by size (reverse)", ["sort size --reverse=yes", "linemode size"]),
        new(", + r", "sort random --reverse=no", "Sort randomly"),
        new("g + h", "cd ~", "Go home"),
        new("g + c", "cd ~/.config", "Go to ~/.config"),
        new("g + d", "cd ~/Downloads", "Go to ~/Downloads"),
        new("g + <Space>", "cd --interactive", "Jump interactively"),
        new("g + f", "follow", "Follow hovered symlink"),
        new("t + t", "tab_create --current", "Create a new tab in CWD"),
        new("t + r", "tab_rename --interactive", "Rename current tab"),
        new("1", "tab_switch 0", "Switch to first tab"),
        new("2", "tab_switch 1", "Switch to second tab"),
        new("3", "tab_switch 2", "Switch to third tab"),
        new("4", "tab_switch 3", "Switch to fourth tab"),
        new("5", "tab_switch 4", "Switch to fifth tab"),
        new("6", "tab_switch 5", "Switch to sixth tab"),
        new("7", "tab_switch 6", "Switch to seventh tab"),
        new("8", "tab_switch 7", "Switch to eighth tab"),
        new("9", "tab_switch 8", "Switch to ninth tab"),
        new("[", "tab_switch -1 --relative", "Switch to previous tab"),
        new("]", "tab_switch 1 --relative", "Switch to next tab"),
        new("{", "tab_swap -1", "Swap current tab with previous tab"),
        new("}", "tab_swap 1", "Swap current tab with next tab"),
        new("w", "tasks:show", "Show task manager"),
        new("~ / <F1>", "help", "Open help"),
    ];
}
